version: "3.9"

services:
  patient-service-db:
    image: postgres:15
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - patient_db_data:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build: ./patientService
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  analytics-service:
    build: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    depends_on:
      - kafka
    networks:
      - internal
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  billing-service:
    build: ./billing-service
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"   # Spring Boot HTTP
      - "9001:9001"   # gRPC
    networks:
      - internal

  kafka:
    image: apache/kafka:4.0.1-rc2
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    networks:
      - internal
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_METADATA_LOG_DIR: /kafka/kraft-metadata
    volumes:
      - kafka_data:/kafka/data
      - kafka_metadata:/kafka/kraft-metadata




  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - patient-service
      - billing-service
      - analytics-service
    networks:
      - internal

volumes:
  patient_db_data:
  kafka_data:
  kafka_metadata:

networks:
  internal:
    driver: bridge
