version: "3.9"

services:
  patient-service-db:
    image: postgres:15
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - patient_db_data:/var/lib/postgresql/data
    networks:
      - internal

  auth-service-db:
    image: postgres:15
    container_name: auth-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build: ./patientService
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - internal

  auth-service:
    build: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "4005:4005"
    depends_on:
      - auth-service-db
      - kafka
    networks:
      - internal



  analytics-service:
    build: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    depends_on:
      - kafka
    networks:
      - internal


  billing-service:
    build: ./billing-service
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"   # Spring Boot HTTP
      - "9001:9001"   # gRPC
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - internal


  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    ports:
      - "29092:29092"   # host access
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      # Internal container network
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal






  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - patient-service
      - billing-service
      - analytics-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    networks:
      - internal


volumes:
  patient_db_data:
  kafka_data:
  kafka_metadata:
  auth_db_data:

networks:
  internal:
    driver: bridge
